### ISSUE TITLE
main.py crashing when user has no mic connected

### ISSUE THREAD

**Issue by wassfila** [TheSoundOfAIOSR/rg_production#20]
It just happened that I had no microphone attached, from the crash it was not obvious, so I think it is better to have a nicer controlled error notification to the user rather than the crash
```shell
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "rg_production\main.py", line 199, in <module>
     loop.run_until_complete(ProdApp().startup())
   File "rg_production\main.py", line 30, in __init__
     self.audio = AudioInterface()
   File "D:\Dev\SoundHacking\project_common\rg_production\common\taudio\AudioInterface.py", line 17, in __init__
     self.devices = self.get_audio_devices()
   File "D:\Dev\SoundHacking\project_common\rg_production\common\taudio\AudioInterface.py", line 126, in get_audio_devices
     audio_device["in"] = sd.query_devices(kind="input")
   File "D:\Dev\SoundHacking\project_common\rg_production\venv\lib\site-packages\sounddevice.py", line 564, in query_devices
     raise PortAudioError('Error querying device {}'.format(device))
 sounddevice.PortAudioError: Error querying device -1
```

After I attached a microphone, that step progressed without errors, as this is an obvious error, it is not high prio, just nice to have

**Comment by nimblefox** [comment]
exception has been handled in 41908eba2dfd9f5aaf2e31c67299caffb9b662f7 , @atjessehill could you enhance it a bit more? 
TODO: make the lab.text say "no audio input found, please insert a mic"
